---
- name: Stop and remove existing Nginx container
  docker_container:
    name: nginx
    state: absent

- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    tag: 1.29.7-alpine
    source: pull
  tags:
    - pull-nginx-image

- name: Copy the Nginx configuration 
  ansible.builtin.copy:
    src: nginx.conf
    dest: /tmp/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:1.29.7-alpine
    restart_policy: unless-stopped
    image_name_mismatch: recreate
    state: started
    ports:
      - "81:80"
    networks:
      - name: custom_net
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf:ro
  tags:
    - run-nginx-container

...
