---
- name: Create a custom Docker network
  community.docker.docker_network:
    name: custom_net
    driver: bridge

- name: Stop and disable system Nginx
  ansible.builtin.service:
    name: nginx.service
    state: stopped
    enabled: false

- name: Stop and remove existing Nginx container
  docker_container:
    name: nginx-proxy
    state: absent

- name: Remove existing nginx.conf if it's in a directory
  ansible.builtin.file:
    path: /tmp/nginx.conf
    state: absent

- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    tag: 1.29.7-alpine
    source: pull
  tags:
    - pull-nginx-image

- name: Copy the Nginx configuration 
  ansible.builtin.copy:
    src: nginx.conf
    dest: /tmp/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: nginx-proxy
    image: nginx:1.29.7-alpine
    restart_policy: unless-stopped
    image_name_mismatch: recreate
    state: started
    ports:
      - "{{app_port}}:80"
    networks:
      - name: custom_net
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf:ro
  tags:
    - run-nginx-container

...
