---
- name: Stop and disable system Nginx
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: no
    ignore_errors: yes

- name: Stop and remove existing Nginx container
  docker_container:
    name: "{{ container_name | default('nginx') }}"
    state: absent

- name: Remove existing nginx.conf if it's in a directory
  ansible.builtin.file:
    path: /tmp/nginx.conf
    state: absent

- name: Create a custom Docker network
  community.docker.docker_network:
    name: custom_net
    driver: bridge

- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    tag: 1.29.7-alpine
    source: pull
  tags:
    - pull-nginx-image

- name: Copy the Nginx configuration 
  ansible.builtin.copy:
    src: nginx.conf
    dest: /tmp/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: "{{ container_name | default('nginx') }}"
    image: nginx:1.29.7-alpine
    restart_policy: unless-stopped
    image_name_mismatch: recreate
    state: started
    ports:
      - "{{nginx_port}}:80"
    networks:
      - name: custom_net
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf:ro
  tags:
    - run-nginx-container

...
