---
- name: Pull Nginx Docker image
  docker_image:
    name: nginx
    tag: nginx:1.28.3-alpine
    source: pull
  tags:
    - pull-nginx-image

- name: Copy the Nginx configuration 
  ansible.builtin.copy:
    src: ../files/nginx.conf
    dest: /tmp/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:1.28.3-alpine
    restart_policy: unless-stopped
    ports:
      - "80:80"
    networks:
      - name: custom_net
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf:ro
  tags:
    - run-nginx-container

- name: Ensure Nginx container is running
  docker_container:
    name: nginx
    state: started
  tags:
    - ensure-nginx-running

...
