---
- name: Deploy webapp content
  hosts: staging, prod
  become: true

  vars_files:
    - vars/logos.yml
    
  roles:  
    # At first, install Docker
    - role: docker
    # Secondly, install Nginx
    - role: nginx
    # Thirdly, start the webapp instance
    - role: webapp
      vars:
        container_name: "webapp"
        app_port: 82

...
