---
- hosts: prod, staging
  become: true
  roles:
    # At first, install Docker
    - role: docker
    # Secondly, install Nginx
    # - role: nginx
    
    # Thirdly, start the webapp instance
    # - role: webapp
    #   vars:
    #     container_name: "webapp1"
    #     app_port: 8082
    #     target_dir: "{%- if ansible_distribution == 'CentOS' -%}/usr/share/nginx/html{%- elif ansible_distribution == 'Ubuntu' -%}/var/www/html{%- endif %}"

...
