---
- name: Deploy webapp content
  hosts: staging, prod
  become: true

  vars_files:
    - vars/logos.yml
  
  # vars:
  #   app_port: 82
  
  roles:  
    # At first, install Docker
    - role: docker
    # Secondly, install Nginx
    - role: nginx
    # Thirdly, start the webapp instance
    - role: webapp

      
...
